name: Extracto CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"
      TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Test Suite
        run: |
          # 1. Install the core app dependencies (like PyPDF2) into the runner's environment
          pip install -r requirements.txt
          
          # 2. Install the testing dependencies (like pytest and moto)
          pip install -r requirements-dev.txt
          
          # 3. Run the tests
          pytest tests/

      - name: Bundle Lambda Dependencies
        run: |
          # Install PyPDF2 directly into the src/ folder so Terraform can zip it for AWS
          pip install -r requirements.txt -t src/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve